### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by stefreak** [vast-engineering/uicollectionview-gridlayout#5]
Hello,

i wanted to use this library and noticed the existence of a podspec file - but i could not install via pod install because the Podspec was not submitted to the Cocoapods repository.

Does something speak against submitting it?

Thank You

**Comment by wtmoose** [comment]
Pod spec submitted for approval

**Comment by wtmoose** [comment]
"VCollectionViewGridLayout" 0.0.2 pod spec pushed.

Also, I added the following note to the readme:

> The original intent of this library was to fix a multitude of animation issues with `UICollectionViewFlowLayout` and batch updates in iOS6. The "Expand" and "Sort & Filter" sample projects illustrate two such issues with side-by-side comparisons of `UICollectionViewFlowLayout` and `VCollectionViewGridLayout`. Note that in iOS7, both of these sample projects work correctly with `UICollectionViewFlowLayout`, so this library may not provide any benefit over `UICollectionViewFlowLayout` beyond sticky headers.

Are you interested in this library for other than sticky headers? I am trying to understand if people are still having problems with `UICollectionViewFlowLayout` animations.
